@startuml
title 書籍管理システムの業務の流れ

start
:書籍の検索と在庫確認;
if (在庫があるか？) then (はい)
  :貸出予約の作成;
  :貸出手続き（図書館スタッフ）;
  :貸出情報の登録;
else (いいえ)
  :予約不可を通知;
endif
:書籍の返却;
:返却手続き（図書館スタッフ）;
:在庫情報の更新;

:管理者の作業;
fork
  :書籍の登録;
fork again
  :書籍情報の編集;
fork again
  :書籍の削除;
endfork

stop

@enduml
