@startuml
title 書籍管理システムの導入目的

:書籍管理システムの導入目的;
note right
  書籍情報の効率的な管理
end note

:書籍情報の一元管理;
:在庫情報の可視化;
:ユーザー利便性の向上;
:業務効率の向上;

:書籍管理システムの導入目的: --> :書籍情報の一元管理;
:書籍管理システムの導入目的: --> :在庫情報の可視化;
:書籍管理システムの導入目的: --> :ユーザー利便性の向上;
:書籍管理システムの導入目的: --> :業務効率の向上;

@enduml
