@startuml
title 書籍管理システムの達成すべき目標

:書籍管理システムの達成すべき目標;
note right
  システム導入による改善点
end note

:情報管理の一元化;
:検索の迅速化;
:在庫管理の効率化;
:業務の省力化;

:書籍管理システムの達成すべき目標: --> :情報管理の一元化;
:書籍管理システムの達成すべき目標: --> :検索の迅速化;
:書籍管理システムの達成すべき目標: --> :在庫管理の効率化;
:書籍管理システムの達成すべき目標: --> :業務の省力化;

@enduml